### ISSUE TITLE
Are reads/writes data-local?

### ISSUE THREAD

**Issue by kostaskougios** [nerdammer/spark-hbase-connector#12]
Hi, sorry, more of a question rather than an issue, but I didn't know where to ask.

This is a very handy library, but I am wondering if all reads/writes are using data-locality, i.e. running within a spark executor straight from the hdfs or does it go via hbase server? It seems it needs to at-least connect to hbase, but does it fetch the data straight from the hdfs files of hbase or from hbase via tcp?

Thanks

**Comment by nibbio84** [comment]
Hi, the library uses data locality as the communication is established between a spark worker and the (possibly) closest region server. The selection of the best allocation of tasks is accomplished by the underlying MapReduce layer.
Communication is TCP based.
