### ISSUE TITLE
ArrayIndexOutOfBoundsException when using HashSaltingProvider

### ISSUE THREAD

**Issue by AlexPerrot** [nerdammer/spark-hbase-connector#13]
Hello,

When adding salting on the rowKeys using `withSalting`, my sparkJob fails with an `ArrayIndexOutOfBoundsException` on `it.nerdammer.spark.hbase.HashSaltingProvider.salt(SaltingProvider.scala:67)`.

The line is:
```scala
 override def salt(rowKey: Array[Byte]): T = salting(hash(rowKey) % salting.size)
```

I think the issue here is that if `hash(rowKey)` is negative, then `hash(rowKey) % salting.size` is also negative, causing the exception.

**Comment by nibbio84** [comment]
You're perfectly right.
I'm going to replace the offending line with:

```scala
override def salt(rowKey: Array[Byte]): T = salting((hash(rowKey) & 0x7fffffff) % salting.size)
```

In develop.

**Comment by nibbio84** [comment]
Merged into master.
Created tag 1.0.1.
Published to maven/ivy2 repo.
