### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by thinmanwang** [nerdammer/spark-hbase-connector#25]
sc.parallelize(mrArray).toHBaseTable(tableName)
      .toColumns("column1", "column2")
      .inColumnFamily("base_info")
      .save()

"Messages Make" is"Error:(55, 29) value toHBaseTable is not a member of org.apache.spark.rdd.RDD[Seq[Any]]
    sc.parallelize(mrArray).toHBaseTable(tableName)"
                            ^

Why?

**Comment by nicolaferraro** [comment]
Check if you have imported all implicits, as explained in the documentation. Also, mrArray must be a tuble or a mapped object in order to write it to a hbase table. If mrArray is an array, it won't compile.

Let me know if it works.

**Comment by thinmanwang** [comment]
yes,mrArray is an ArrayBuffer.How to turn an ArrayBuffer to a mapped object?
