### ISSUE TITLE
dependency not found: org.codehaus.jackson#jackson-core-asl;1.8.3

### ISSUE THREAD

**Issue by trungtv** [nerdammer/spark-hbase-connector#31]
Hey Nicolas, 
Thanks for the great job. 
I am trying to run the following spark-shell:
`spark-shell --packages it.nerdammer.bigdata:spark-hbase-connector_2.10:1.0.3
`
But it seems that jackson-core-als is mis-dependent. It's not going to download anywhere. Could you please recheck? 
`::: WARNINGS
		[NOT FOUND  ] org.codehaus.jackson#jackson-core-asl;1.8.3!jackson-core-asl.jar (0ms)

	==== local-m2-cache: tried

	  file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.3/jackson-core-asl-1.8.3.jar
`

**Comment by thomastriplet** [comment]
@trungtv I'm having the same issue when using the `--package `, how did you solve it?

**Comment by laxmikata305** [comment]
@trungtv, @thomastriplet , I have same issue here, if you are able to resolve this issue, could you post the fix
