### ISSUE TITLE
Reading multiple column families

### ISSUE THREAD

**Issue by AbhiMadav** [nerdammer/spark-hbase-connector#35]
Looking at the basic API's I understand ways to read multiple columns from a single column family, is there any way of having multiple column families too? As such column family cannot be an array, right? Thanks!

**Comment by nicolaferraro** [comment]
You can read columns from multiple column families by using prefixes in column names. Eg. `cf1:col1`, `cf2:col1` are different columns from different column families.

It is explained [here](https://github.com/nerdammer/spark-hbase-connector#using-different-column-families).
