### ISSUE TITLE
Persisting Collections type in Hbase

### ISSUE THREAD

**Issue by Elbehery** [nerdammer/spark-hbase-connector#52]
I have tried to follow the How-Use-Guide, it worked perfectly for Primitve Types, however, when I tried to use Collections Types, I received 

{ error: value toHBaseTable is not a member of org.apache.spark.rdd.RDD[(String, Int, String, scala.collection.immutable.Map[Int,String])]
       rddMap.toHBaseTable("testMap").
}

I guess the collections are not supported yet, is it ?! 

The code I have used as follows 

{
val rddMap = sc.parallelize(1 to 100).map(i => (i.toString, i+1, "Hello", Map(i -> "Hello")))

***** // write to hbase
rddMap.toHBaseTable("testMap").
toColumns("c1", "c2", "c3").
inColumnFamily("cf").
save()

}

**Comment by onesuper** [comment]
There are several primitive types being implemented through `Bytes.toBytes()`.

see: https://github.com/nerdammer/spark-hbase-connector/blob/12a610b6502aaa92e26f0a90cb95ab10ffa3cd93/src/main/scala/it/nerdammer/spark/hbase/conversion/FieldWriter.scala

**Comment by Elbehery** [comment]
But this is not sufficient .. Everyone uses custom data types I guess !!!
