### ISSUE TITLE
Deal With NA When Write Into HBaseTable

### ISSUE THREAD

**Issue by lzm7455** [nerdammer/spark-hbase-connector#53]
Hi Man,
     When I try to save a rdd into hbase , how could I get rid of the NA (like "", "null", "NA" or else) value?

```scala
    trdd.toHBaseTable("mbk_user_label")
      .toColumns("mobikeno", "registertime", "ts", "progress", "nation", "status", "citycode")
      .inColumnFamily("attrs")
      .save()
```
trdd: org.apache.spark.rdd.RDD[(String, String, String, String, String, String, String, String)]

Should I  change my `trdd` into Option[String]?

Thx.

**Comment by lzm7455** [comment]
I change to use option to fix the NA like problem with a func. 
However when all the data are None, it will raise a Error.
Does it possible to cover this situation in your proj?

**Comment by nicolaferraro** [comment]
Technically, you cannot have a empty row id, so you should not put Optional values on them. If you need to use Optionals also on row id, you can just filter them out (`rdd.filter(_._1.nonEmpty).toColumns...` before writing them to the store.

I'd not like to suppress the error as it may indicate a problem with your code.

**Comment by lzm7455** [comment]
Thx. 
Sorry for not explain the problem clear. I give a real row id but all the field value is None. Now I add filter func before load data into HBase.
Make it right as your suggest.
