### ISSUE TITLE
Spark Streaming context 

### ISSUE THREAD

**Issue by tarekabouzeid** [nerdammer/spark-hbase-connector#6]
i am using spark streaming context to take flume stream and process it using spark , then want to save the Dstream into Hbase , is it possible to do so using your library ? Thanks in advance

**Comment by nibbio84** [comment]
I will provide this functionality with next release.

**Comment by tarekabouzeid** [comment]
thanks so much

**Comment by nibbio84** [comment]
Fixed with pull request https://github.com/nerdammer/spark-hbase-connector/pull/7

**Comment by nibbio84** [comment]
Starting with version 1.0.0 the streaming version looks like:

```scala
stream.foreachRDD(rdd =>
    rdd.toHBaseTable("table")
      .inColumnFamily("cf")
      .toColumns("col1")
      .save()
    )
```

This allowed to remove the direct dependency from Spark-Streaming and having a cleaner code.
