### ISSUE TITLE
Continuously INFO JobScheduler: Added jobs for time

### ISSUE THREAD

**Issue by Chabane** [nerdammer/spark-hbase-connector#66]
Hello @nicolaferraro,

Thanks for sharing,

I tried to integrate `spark-hbase-connector` with Kafka Spark Streaming and I have a looping message :

See the code here :
https://github.com/Chabane/bigdata-spark-kafka-full-example/blob/develop/streaming/src/main/scala/com/mitosis/Main.scala#L123

```
17/12/26 21:36:35 INFO JobScheduler: Added jobs for time 1514324195000 ms
17/12/26 21:36:40 INFO JobScheduler: Added jobs for time 1514324200000 ms
```
I tried with `--master local[*]` and I have the same issue,

Do you have any idea?

**Comment by nicolaferraro** [comment]
Hi @Chabane, sorry for delay. I see you have changed completely your code. Do you still need help?

**Comment by Chabane** [comment]
@nicolaferraro 

Hello, thanks for your reply!

The issue was related to my hbase configuration.

So it fixed now :+1:
