### ISSUE TITLE
Whether to support kerberos authentication access?

### ISSUE THREAD

**Issue by highfei2011** [nerdammer/spark-hbase-connector#67]
Whether to support kerberos authentication access? Thank you.

**Comment by nicolaferraro** [comment]
Hi @highfei2011. Kerberos authentication should be already supported, since the whole hbase configuration can be specified in the `hbase-site.xml` file. See [this section of the doc](https://github.com/nerdammer/spark-hbase-connector#setting-the-hbase-host) for more info.

Does it work for you?

**Comment by highfei2011** [comment]
Thanks,It works fine, but does it seem like it can not support spark2.2.0?
