### ISSUE TITLE
how do i apply a customized partitioner to hBaseRDD?

### ISSUE THREAD

**Issue by gypsysunny** [nerdammer/spark-hbase-connector#69]
val hBaseRDD = sc.hbaseTable[(String, Int, String)]("mytable")
    .select("column1", "column2")
    .inColumnFamily("mycf")

thank you.

**Comment by nicolaferraro** [comment]
Hi @gypsysunny, what you mean by custom partitioner? The connector allows you to use salting to randomize the prefix on the keys in order to spread them. Setting regions is something that should be at table creation time outside the scope of the connector.

**Comment by gypsysunny** [comment]
i mean a custom partitioner analagous to HashPartitioner. and i have got a way to do that.
thank you.
