### ISSUE TITLE
Counter fields support

### ISSUE THREAD

**Issue by edgefox** [nerdammer/spark-hbase-connector#9]
Hi!
Just wondering if you are planning to add support for counter fields(http://hbase.apache.org/book.html#_counters) or maybe I missed it somewhere?

**Comment by nibbio84** [comment]
Not sure if it would be useful to include them, as Spark has a better support for counter-like fields aka accumulators (with built-in fault tolerance).

Spark's accumulators can be stored to normal hbase fields with the library (just wrap them in single-valued RDDs).
